### Register a new user
POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "password": "string"
}

### Login user
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "string",
  "password": "string"
}

### Get the list of dinners
GET {{host}}/api/v1.0/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGRiYmFkNy05M2Q1LTQwMWItODQzMi1hNjNhNjhmNTQ1Y2MiLCJnaXZlbl9uYW1lIjoiUG9veWEiLCJmYW1pbHlfbmFtZSI6IkFsYW1pcnBvdXIiLCJqdGkiOiIyYTI4OGQyNy0yM2RlLTQ5ZjAtOTRmNi1hODM2ZmY0MmFhMDkiLCJleHAiOjE2OTU2MDE2MjcsImlzcyI6IlBvb3lhLkFsYW1pcnBvdXIiLCJhdWQiOiJQb295YS5BbGFtaXJwb3VyIn0.d5J61-V1mbU9EO9DHcw4ypmuokGTHdVZ7v3WGXA9Hhw